// article.js - Données des articles pour Eloria

const articlesData = [
{
    id: 1,
    titre: "Se détacher du regard des autres : retrouver sa liberté intérieure ✨",
    imageCarte: "article1.jpg",
    imageHero: "article1.jpg",
    imageSecondaire: "article1b.png",
    auteur: "Ansima Babeho, Fondatrice d'Eloria",
    date: "15 janvier 2026",
    description: "Un guide pour apprendre à s'affranchir du regard des autres et retrouver son authenticité, sa liberté intérieure et sa propre lumière.",
    contenu: [
        { type: "paragraphe", texte: "Pendant longtemps, on apprend à se définir à travers les autres. Leurs avis. Leurs attentes. Leurs réactions. Sans même s'en rendre compte, on ajuste nos paroles, nos choix, parfois même nos rêves, pour être accepté·e, compris·e ou validé·e." },
        { type: "paragraphe", texte: "Mais grandir, c'est comprendre une chose essentielle : le regard des autres ne définit pas ta valeur." },
        
        { type: "titre", texte: "Pourquoi le regard des autres pèse autant" },
        { type: "paragraphe", texte: "Le besoin d'appartenance est naturel. Nous voulons être aimés, reconnus, respectés." },
        { type: "paragraphe", texte: "Le problème commence lorsque ce besoin devient une dépendance. Quand tu n'oses plus être toi-même par peur du jugement. Quand tu doutes de ce que tu ressens parce que quelqu'un ne comprend pas. Quand tu vis pour être approuvé·e plutôt que pour être aligné·e." },
        { type: "paragraphe", texte: "À ce moment-là, tu t'éloignes doucement de toi." },
       
        { type: "titre", texte: "Le regard des autres est limité" },
        { type: "paragraphe", texte: "Chaque personne te perçoit à travers :" },
        { type: "sous-titre", texte: "· sa propre histoire" },
        { type: "sous-titre", texte: "· ses blessures" },
        { type: "sous-titre", texte: "· ses croyances" },
        { type: "sous-titre", texte: "· ses peurs" },
        { type: "paragraphe", texte: "Autrement dit, les autres ne te voient jamais entièrement. Ils voient une version filtrée de toi." },
        { type: "paragraphe", texte: "Fonder ta valeur sur quelque chose d'aussi subjectif, c'est te placer dans une instabilité permanente." },
        
        { type: "titre", texte: "Se détacher ne veut pas dire devenir froid·e" },
        { type: "paragraphe", texte: "Se détacher du regard des autres, ce n'est pas ignorer tout le monde. Ce n'est pas devenir insensible." },
        { type: "paragraphe", texte: "C'est apprendre à faire la différence entre :" },
        { type: "sous-titre", texte: "· les avis qui construisent" },
        { type: "sous-titre", texte: "· et ceux qui projettent" },
        { type: "paragraphe", texte: "C'est écouter sans absorber. Recevoir sans se perdre." },
        
        { type: "titre", texte: "Revenir à soi" },
        { type: "paragraphe", texte: "Le vrai tournant commence quand tu te poses ces questions :" },
        { type: "sous-titre", texte: "· Est-ce que ce choix me ressemble ?" },
        { type: "sous-titre", texte: "· Est-ce que je le fais par envie ou par peur ?" },
        { type: "sous-titre", texte: "· Est-ce que je me respecte dans cette situation ?" },
        { type: "paragraphe", texte: "Plus tu t'écoutes, moins le bruit extérieur a de pouvoir sur toi." },

        { type: "titre", texte: "Le courage d'être soi" },
        { type: "paragraphe", texte: "Il faut du courage pour être authentique. Pour déplaire parfois. Pour être incompris·e." },
        { type: "paragraphe", texte: "Mais il faut encore plus de courage pour continuer à vivre une vie qui n'est pas la tienne." },
        { type: "paragraphe", texte: "Quand tu choisis d'être toi, certaines personnes s'éloignent. D'autres arrivent. Et surtout, tu te retrouves." },
        
        { type: "titre", texte: "ELORIA et la liberté intérieure" },
        { type: "paragraphe", texte: "Chez ELORIA, nous croyons que le glow up le plus profond est invisible." },
        { type: "paragraphe", texte: "C'est celui qui te permet de :" },
        { type: "sous-titre", texte: "· te choisir " },
        { type: "sous-titre", texte: "· t'exprimer" },
        { type: "sous-titre", texte: "· exister" },
        { type: "paragraphe", texte: "Se détacher du regard des autres, c'est s'offrir une liberté intérieure." },
        
        { type: "titre", texte: "Grandir, pour soi" },
        { type: "paragraphe", texte: "Tu n'as pas besoin d'être compris·e par tout le monde. Tu as besoin d'être en paix avec toi-même." },
        { type: "paragraphe", texte: "✨ Quand tu choisis ton regard plutôt que celui des autres, tu commences vraiment à évoluer." }
    ],
    auteurBio: "Ansima Babeho est la fondatrice d'Eloria. Élève en humanités pédagogiques avec une passion pour la psychologie, elle a créé cette plateforme après avoir constaté le besoin d'espaces d'échange authentiques entre adolescentes. Entre les ateliers qu'elle anime dans son école et les articles qu'elle rédige, elle cherche à créer des ponts entre les cœurs et les esprits."
},
{
    id: 2,
    titre: "Love Languages : Ton manuel pour ne plus 'ghost' les cœurs ✨",
    imageCarte: "article2.jpg",
    imageHero: "article2.jpg",
    imageSecondaire: "article2b.jpg",
    auteur: "Ansima Babeho, Fondatrice d'Eloria",
    date: "20 janvier 2026",
    description: "Décryptage des 5 langages de l'amour : comment parler le bon dialecte émotionnel pour des relations plus authentiques et éviter les malentendus sentimentaux.",
    contenu: [
        { type: "paragraphe", texte: "T'as déjà eu l'impression de donner tout ton lore à quelqu'un, mais qu'en face, le signal ne passe pas ? C'est normal. On a tous une fréquence radio différente pour l'amour. Gary Chapman a théorisé ça, mais on va le traduire en version 2026, entre poésie brute et vibes Pinterest." },
        { type: "titre", texte: "🕯️ Le Concept (The Plot)" },
        { type: "paragraphe", texte: "L'amour, c'est comme une langue étrangère. Si tu parles en 'Services Rendus' à quelqu'un qui ne comprend que les 'Mots Doux', c'est comme essayer de lire un livre en braille avec les yeux : tu passes à côté de l'essentiel. L'enjeu ? Remplir le 'réservoir émotionnel' de l'autre avant qu'il ne tombe en mode économie d'énergie." },
        { type: "titre", texte: "☁️ Les 5 Langages (The Aesthetic Breakdown)" },
        { type: "titre", texte: "1. 💬 Les Paroles (Words of Affirmation)" },
        { type: "sous-titre", texte: "Le concept : Pour eux, le silence est stressant. Ils ont besoin d'entendre ce que tu penses." },
        { type: "sous-titre", texte: "C'est quoi ? Des compliments, des encouragements, ou juste un 'je suis là'." },
        { type: "sous-titre", texte: "En mode simple : Un SMS 'T'es incroyable' > un cadeau à 50$." },
        { type: "sous-titre", texte: "L'effet : Ça booste leur confiance instantanément." },
        { type: "titre", texte: "2. 🕒 Le Temps (Quality Time)" },
        { type: "sous-titre", texte: "Le concept : Pour eux, 'être ensemble' ne veut pas dire 'être dans la même pièce sur TikTok'." },
        { type: "sous-titre", texte: "C'est quoi ? Une vraie discussion, une balade, ou regarder un film en mode 'avion'." },
        { type: "sous-titre", texte: "En mode simple : 15 min sans téléphone > 3 heures à scroller l'un à côté de l'autre." },
        { type: "sous-titre", texte: "L'effet : Ils se sentent prioritaires." },
        { type: "titre", texte: "3. 🎁 Les Cadeaux (Receiving Gifts)" },
        { type: "sous-titre", texte: "Le concept : Ce n'est pas une question d'argent, c'est la preuve que tu as pensé à eux quand ils n'étaient pas là." },
        { type: "sous-titre", texte: "C'est quoi ? Un petit truc qui rappelle un souvenir, leur boisson préférée, une fleur." },
        { type: "sous-titre", texte: "En mode simple : 'J'ai vu ça, j'ai pensé à toi' = la phrase magique." },
        { type: "sous-titre", texte: "L'effet : Ils se sentent précieux." },
        { type: "titre", texte: "4. 🛠️ Les Services (Acts of Service)" },
        { type: "sous-titre", texte: "Le concept : Les mots ne comptent pas, seules les actions prouvent l'amour." },
        { type: "sous-titre", texte: "C'est quoi ? T'aider pour un devoir, ranger un truc à ta place, te ramener à manger." },
        { type: "sous-titre", texte: "En mode simple : 'Laisse, je m'en occupe' > 1000 'Je t'aime'." },
        { type: "sous-titre", texte: "L'effet : Ils se sentent soutenus et moins seuls." },
        { type: "titre", texte: "5. 🫂 Le Toucher (Physical Touch)" },
        { type: "sous-titre", texte: "Le concept : La peau est leur capteur d'émotions principal. Pas besoin de parler." },
        { type: "sous-titre", texte: "C'est quoi ? Un câlin, se tenir la main, ou juste s'asseoir épaule contre épaule." },
        { type: "sous-titre", texte: "En mode simple : Une main tenue en marchant suffit à les rassurer." },
        { type: "sous-titre", texte: "L'effet : Ils se sentent en sécurité." },
        { type: "titre", texte: "⚡ Le 'Quick Check' pour savoir" },
        { type: "paragraphe", texte: "Pour trouver ton langage, demande-toi : 'Qu'est-ce qui me manque le plus quand je suis triste ?'" },
        { type: "sous-titre", texte: "Si c'est un câlin ➔ Toucher" },
        { type: "sous-titre", texte: "Si c'est qu'on me dise que ça va aller ➔ Paroles" },
        { type: "sous-titre", texte: "Si c'est qu'on vienne me voir ➔ Temps" },
        { type: "sous-titre", texte: "Si c'est qu'on me ramène mon plat préféré ➔ Cadeaux" },
        { type: "sous-titre", texte: "Si c'est qu'on m'aide à finir mon travail ➔ Services" },
        { type: "titre", texte: "✨ Le mot de la fin" },
        { type: "paragraphe", texte: "L'erreur n°1 ? Donner ce que TU veux recevoir." },
        { type: "titre", texte: "✨ Le Red Flag à éviter" },
        { type: "paragraphe", texte: "N'offre pas ce que tu veux recevoir. Apprends à lire la notice de l'autre. Si sa langue maternelle c'est le Toucher, tes longs discours (Words) ne seront que du vent s'ils ne sont pas accompagnés d'une main tenue." },
        { type: "titre", texte: "🗝️ Conclusion" },
        { type: "paragraphe", texte: "Connaître ton 'Love Language', c'est ton Main Character Energy. C'est arrêter de deviner et commencer à construire. Alors, c'est quoi ton dialecte ?" },
        { type: "paragraphe", texte: "Stay soft. Stay real. 🦋" }
    ],
    auteurBio: "Ansima Babeho est la fondatrice d'Eloria. Élève en humanités pédagogiques avec une passion pour la psychologie, elle a créé cette plateforme après avoir constaté le besoin d'espaces d'échange authentiques entre adolescentes. Entre les ateliers qu'elle anime dans son école et les articles qu'elle rédige, elle cherche à créer des ponts entre les cœurs et les esprits."
},
{
    id: 3,
    titre: "🥀 Shadow Love : Pourquoi la Dark Romance casse Internet ?",
    imageCarte: "article3.jpg",
    imageHero: "article3.jpg",
    imageSecondaire: "article3b.jpeg",
    auteur: "Ansima Babeho, Fondatrice d'Eloria",
    date: "25 janvier 2026",
    description: "Analyse sociologique de l'engouement pour la Dark Romance sur #BookTok : entre quête d'intensité, exploration psychologique et questionnement sur les limites de la fiction.",
    contenu: [
        { type: "paragraphe", texte: "Si tu traînes sur #BookTok, tu n'as pas pu passer à côté : couvertures sombres, roses épineuses et esthétique 'Dark Academia'. La Dark Romance est devenue un véritable raz-de-marée culturel. Mais qu'est-ce qui se cache derrière ce besoin collectif de lire des histoires qui flirtent avec l'interdit ?" },
        { type: "paragraphe", texte: "On a décrypté pour vous les codes de cette tendance qui fascine autant qu'elle interroge. 🕯️🕵️" },
        { type: "titre", texte: "🌑 Le 'Lore' du Genre : De quoi on parle ?" },
        { type: "paragraphe", texte: "La Dark Romance, c'est l'opposé radical de la comédie romantique 'feel-good'. Ici, on entre dans les zones grises de la psychologie humaine." },
        { type: "sous-titre", texte: "L'ambiance : Un amour qui franchit les lignes rouges. On y croise souvent des thèmes d'obsession, de pouvoir et de rédemption." },
        { type: "sous-titre", texte: "Le 'Anti-Hero' : Un personnage souvent toxique ou 'brisé', qui devient le centre d'une fascination intense pour des millions de lecteurs." },
        { type: "sous-titre", texte: "Le concept : Explorer la part d'ombre pour y trouver une lueur d'humanité." },
        { type: "titre", texte: "✨ Les Clés du Succès (The Trend Breakdown)" },
        { type: "titre", texte: "1. L'Adrénaline Émotionnelle 🌪️" },
        { type: "paragraphe", texte: "Dans un monde parfois trop lisse, ces récits proposent une évasion sans filtre." },
        { type: "sous-titre", texte: "L'analyse : C'est comme un film d'horreur, mais pour le cœur. Les lecteurs cherchent des émotions multipliées par 1000 pour sortir de la routine quotidienne." },
        { type: "titre", texte: "2. Le Laboratoire des Limites 🧪" },
        { type: "paragraphe", texte: "C'est un espace sécurisé pour observer des comportements qu'on ne tolérerait jamais dans la vraie vie." },
        { type: "sous-titre", texte: "L'analyse : C'est une exploration psychologique. On teste ses propres limites et ses valeurs depuis la sécurité de son canapé, sans aucun risque réel." },
        { type: "titre", texte: "3. L'Effet de Communauté #BookTok 🤝" },
        { type: "paragraphe", texte: "Plus qu'une lecture, c'est un mouvement social." },
        { type: "sous-titre", texte: "L'analyse : La tendance vit à travers les 'POV' et les réactions virales. Le plaisir vient autant de la discussion avec la communauté que de la lecture elle-même." },
        { type: "titre", texte: "⚠️ Reality Check : Garder ses 'Red Flags' à l'œil" },
        { type: "paragraphe", texte: "Le succès de ces livres pose aussi des questions sur la perception des relations." },
        { type: "sous-titre", texte: "La Frontière Fiction vs Réalité : Ce qui est présenté comme 'passionnel' dans ces romans (contrôle, jalousie extrême) est souvent le premier signe d'une relation toxique IRL. 🚩" },
        { type: "sous-titre", texte: "Le Rôle des Trigger Warnings : Ces avertissements sont essentiels. Ils rappellent que le contenu est sensible et qu'il ne doit pas être consommé sans recul." },
        { type: "sous-titre", texte: "La Construction du Consentement : En bousculant les règles, ces fictions obligent paradoxalement à se rappeler que dans la vraie vie, le respect est la seule base solide." },
        { type: "titre", texte: "🕯️ Vers une Lecture Éclairée ?" },
        { type: "paragraphe", texte: "L'idée n'est pas de juger ce que les autres lisent, mais de comprendre la dynamique :" },
        { type: "sous-titre", texte: "Distinguer le Fantasme du Modèle : Apprécier une fiction sombre ne signifie pas vouloir la vivre. C'est la base de l'esprit critique." },
        { type: "sous-titre", texte: "Le Dialogue : Ces livres sont des points de départ pour parler de sujets complexes : pouvoir, limites et respect." },
        { type: "sous-titre", texte: "L'Équilibre : Le phénomène montre surtout un besoin de récits 'sans filtre' dans une société qui cherche souvent à tout lisser." },
        { type: "titre", texte: "🗝️ Conclusion" },
        { type: "paragraphe", texte: "La Dark Romance est le miroir d'une génération en quête d'intensité. C'est un genre qui ose explorer les recoins du cœur humain, là où la morale devient floue. Le vrai défi pour les lecteurs ? Savoir fermer le livre et laisser les ombres à l'intérieur, pour ne garder que la lumière dans la réalité." },
        { type: "paragraphe", texte: "Analyze the trend. Keep your eyes open. 🥀📖" }
    ],
    auteurBio: "Ansima Babeho est la fondatrice d'Eloria. Élève en humanités pédagogiques avec une passion pour la psychologie, elle a créé cette plateforme après avoir constaté le besoin d'espaces d'échange authentiques entre adolescentes. Entre les ateliers qu'elle anime dans son école et les articles qu'elle rédige, elle cherche à créer des ponts entre les cœurs et les esprits."
},

    {
        id: 4,
        titre: "Attirance, Crush, Admiration ou Amour : Décryptage des Sentiments",
        imageCarte: "article4.jpg",
        imageHero: "article4.jpg",
        imageSecondaire: "article4b.jpg",
        auteur: "Ansima Babeho, Fondatrice d'Eloria",
        date: "24 décembre 2026",
        description: "Une analyse approfondie pour distinguer l'attirance, le crush, l'admiration et l'amour véritable, surtout à l'adolescence où ces sentiments sont souvent confondus.",
        contenu: [
            { type: "paragraphe", texte: "Ce sont des états distincts qui sont souvent confondus, surtout à l'adolescence où tout est intense et nouvellement expérimenté. Voici une analyse pour clarifier chaque notion :" },
            { type: "titre", texte: "1. L'Attirance" },
            { type: "paragraphe", texte: "C'est le plus instinctif et sensoriel." },
            { type: "sous-titre", texte: "· Cœur : C'est physique, chimique. Une réaction immédiate." },
            { type: "sous-titre", texte: "· Source : Le regard, la voix, la manière de bouger, une énergie qui vous captive." },
            { type: "sous-titre", texte: "· Pensée type : « Je veux être près d'elle/lui. » « Je le/la trouve irrésistible. »" },
            { type: "sous-titre", texte: "· Durée & profondeur : Peut être instantané et passager. Ne nécessite pas de connaître la personne." },
            { type: "sous-titre", texte: "· Analogies : C'est comme avoir faim ou soif. C'est un appétit." },
            { type: "titre", texte: "2. Le Crush / La Fixation passagère" },
            { type: "paragraphe", texte: "C'est une construction mentale et fantasmatique." },
            { type: "sous-titre", texte: "· Cœur : C'est une projection, une idéalisation. On est « accro » à l'idée qu'on se fait de la personne." },
            { type: "sous-titre", texte: "· Source : Son statut ( le/la mystérieux(se)),le plus populaire, un talent, un style, ou simplement le fait qu'il/elle vous ait souri." },
            { type: "sous-titre", texte: "· Pensée type : « Et si... ? » On imagine des scénarios, des conversations. C'est souvent secret, ruminé." },
            { type: "sous-titre", texte: "· Durée & profondeur : Temporaire (de quelques jours à quelques mois). S'efface souvent dès qu'on connaît vraiment la personne ou qu'un nouvel objet d'attention apparaît." },
            { type: "sous-titre", texte: "· Le piège : On n'aime pas la personne réelle, avec ses défauts et sa complexité, mais une version édulcorée et parfaite créée dans sa tête. C'est un sentiment égo-centré (il/elle me fait ressentir quelque chose)." },
            { type: "titre", texte: "3. L'Admiration" },
            { type: "paragraphe", texte: "C'est un sentiment tourné vers l'autre, basé sur le respect." },
            { type: "sous-titre", texte: "· Cœur : C'est intellectuel ou moral. On reconnaît une qualité, un talent, une force chez quelqu'un." },
            { type: "sous-titre", texte: "· Source : Son intelligence, sa gentillesse, sa persévérance, son art." },
            { type: "sous-titre", texte: "· Pensée type : « Je respecte énormément ce qu'il/elle fait/est. » « Il/elle m'inspire. »" },
            { type: "sous-titre", texte: "· Durée & profondeur : Peut être durable et n'implique aucun désir de possession. On peut admirer un mentor, un ami, une célébrité, sans aucune attirance ou crush." },
            { type: "sous-titre", texte: "· La nuance : Un crush peut contenir de l'admiration, mais l'admiration est pure et ne cherche pas forcément de réciprocité ou de proximité intime." },
            { type: "titre", texte: "4. Aimer quelqu'un (au sens amoureux)" },
            { type: "paragraphe", texte: "C'est le sentiment le plus complexe, mature et engageant. Il intègre et dépasse les autres." },
            { type: "sous-titre", texte: "· Cœur : C'est un choix actif et continu, basé sur une connaissance réelle de l'autre, dans sa globalité (qualités et défauts)." },
            { type: "sous-titre", texte: "· Source : La complicité, la confiance absolue, le respect mutuel, l'engagement, l'acceptation profonde." },
            { type: "sous-titre", texte: "· Pensée type : « Je veux son bonheur, même s'il ne passe pas toujours par moi. » « Je le/la connais et je le/la choisis tous les jours. »" },
            { type: "sous-titre", texte: "· Durée & profondeur : Requiert du temps et de l'action. C'est regarder la personne en face, et non une projection. Cela implique de la vulnérabilité, des compromis, du soutien inconditionnel dans les moments difficiles." },
            { type: "sous-titre", texte: "· Le test décisif : L'amour survit aux désillusions, aux conflits (bien gérés) et au temps. Il n'est pas centré sur ce que la personne vous apporte, mais sur ce que vous construisez et partagez ensemble." },
            { type: "titre", texte: "Conclusion" },
            { type: "paragraphe", texte: "À l'adolescence, on expérimente beaucoup les trois premiers (attirance, crush, admiration), souvent avec une intensité qui les fait paraître être de l'amour. L'amour véritable est le sentiment qui se révèle être solide après que la tempête des premiers émois se soit calmée." }
        ],
        auteurBio: "Ansima Babeho est la fondatrice d'Eloria. Élève en humanités pédagogiques avec une passion pour la psychologie, elle a créé cette plateforme après avoir constaté le besoin d'espaces d'échange authentiques entre adolescentes. Entre les ateliers qu'elle anime dans son école et les articles qu'elle rédige, elle cherche à créer des ponts entre les cœurs et les esprits."
    },
{
    id: 5,
    titre: "Les Rôles Invisibles de l'Enfance : Comment Ils Sculptent Notre Vie d'Adulte",
    imageCarte: "article5.jpg",
    imageHero: "article5.jpg",
    imageSecondaire: "article5b.jpg",
    auteur: "Ansima Babeho, Fondatrice d'Eloria",
    date: "5 janvier 2026",
    description: "Décryptage des 8 rôles familiaux que les enfants adoptent pour survivre émotionnellement, et comment ces schémas continuent à influencer nos vies d'adultes sans que nous en ayons conscience.",
    contenu: [
        { type: "paragraphe", texte: "Chaque famille est un petit système avec ses propres règles et besoins. L'enfant, pour survivre émotionnellement et garder un lien vital avec ses parents, va inconsciemment incarner un rôle qui comble un vide ou maintient l'équilibre (même malsain) du système." },
        { type: "paragraphe", texte: "Voici ce que ces rôles fabriquent comme adulte, souvent à notre insu :" },
        { type: "titre", texte: "· L'Enfant Parfait / Le Sauveur :" },
        { type: "sous-titre", texte: "· Moteur caché : « Si je suis parfait(e) et que je réussis, je vais enfin combler le vide/la tristesse de ma mère/de mon père. Je vais réparer la famille. »" },
        { type: "sous-titre", texte: "· Devenir adulte : C'est la personne fiable à l'extrême, souvent en burnout. Au travail, elle accumule les projets et ne délègue pas (car personne ne fera « aussi bien »). En couple, elle se transforme en thérapeute, cherchant à « sauver » ou « améliorer » son partenaire. Sa peur la plus profonde ? Être médiocre ou inutile, car c'est son identité même qui s'effondre." },
        { type: "titre", texte: "· Le Bouc Émissaire / Le Rebelle :" },
        { type: "sous-titre", texte: "· Moteur caché : « Mon rôle, c'est d'être le problème. Comme ça, tout le monde est d'accord sur un point : c'est de ma faute. Cela évite de regarder les vrais problèmes (l'alcool d'un parent, un mariage qui bat de l'aile...). »" },
        { type: "sous-titre", texte: "· Devenir adulte : Deux destins possibles. Soit on continue à saboter inconsciemment sa vie (relations, boulot) pour rester fidèle à ce rôle familier de « celui qui déraille ». Soit, à l'inverse, on devient hyper-contrôlant, rigide, pour ne surtout jamais reproduire ce chaos. Mais cette personne garde souvent une sensibilité aiguë à l'injustice et une méfiance envers l'autorité." },
        { type: "titre", texte: "· L'Enfant-Parent / Le Médiateur :" },
        { type: "sous-titre", texte: "· Moteur caché : « Je dois être mature, calme et raisonnable. Mes besoins d'enfant sont secondaires. Le bien-être émotionnel de mes parents ou de mes frères et sœurs dépend de moi. »" },
        { type: "sous-titre", texte: "· Devenir adulte : C'est l'ami(e) sur qui tout le monde compte, le/la collègue qui gère les conflits. Mais à l'intérieur, c'est l'épuisement et une colère rentrée. En couple, cette personne a du mal à recevoir et à se laisser choyer ; elle est plus à l'aise dans le rôle du soignant. Elle se sent responsable des émotions des autres, et culpabilise si elle pense à elle." },
        { type: "titre", texte: "· Le Clown :" },
        { type: "sous-titre", texte: "· Moteur caché : « L'atmosphère est lourde. Je sens que maman est triste, que papa est en colère. Si je fais le pitre, ils vont sourire et oublier. Ma tristesse, je la garde pour moi. »" },
        { type: "sous-titre", texte: "· Devenir adulte : C'est la personne drôle et charmante, le soleil de son groupe. Mais elle est souvent incomprise dans sa profondeur. On ne la prend pas au sérieux quand elle va mal (« Ah, toi, tu plaisantes toujours ! »). Elle peut avoir du mal avec l'intimité émotionnelle, car son réflexe est de dédramatiser par une blague au moment crucial. Sa tristesse est souvent solitaire." },
        { type: "titre", texte: "Le piège ultime" },
        { type: "paragraphe", texte: "Ces rôles nous ont sauvés enfant. Ils nous ont donné une place, une identité, une manière de recevoir un peu d'amour. À l'âge adulte, devenus inadaptés, ils sont pourtant si familiers qu'on les confond avec notre personnalité véritable." },
        { type: "titre", texte: "Les Autres Rôles Invisibles de l'Enfance" },
        { type: "titre", texte: "5. L'Enfant Invisible / Le Fantôme" },
        { type: "sous-titre", texte: "· Origine : Naît dans une famille où les parents sont émotionnellement absents (dépression, deuil, travail excessif) ou bien où un autre enfant (souvent malade, handicapé ou 'problématique') monopolise toute l'attention." },
        { type: "sous-titre", texte: "· Moteur caché : « Je ne dois pas en demander plus. Je dois me débrouiller seul(e), être discret(e), ne pas ajouter de fardeau. Mon existence passe au second plan. »" },
        { type: "sous-titre", texte: "· Devenir adulte : C'est la personne extrêmement indépendante, parfois à la limite de l'isolement. Elle a du mal à demander de l'aide (car elle n'y a pas été habituée) et peut se sentir mal à l'aise quand on s'intéresse à elle de trop près. Au travail, elle est celle qui fait un travail remarquable dans l'ombre, mais qui évite les promotions ou les feux des projecteurs. Dans l'amitié ou le couple, elle peut paraître distante ou fuyante, car la proximité est un territoire inconnu et anxiogène. Sa peur profonde : Être un fardeau ou être absorbé(e) et perdre son autonomie." },
        { type: "titre", texte: "6. L'Enfant Parentifié / Le Petit Adulte" },
        { type: "sous-titre", texte: "· À ne pas confondre totalement avec le Médiateur. Ici, l'enfant doit assumer des tâches concrètes et domestiques bien au-delà de son âge." },
        { type: "sous-titre", texte: "· Origine : Parent malade, absent physiquement, immature ou en situation de précarité. L'enfant fait la cuisine, le ménage, s'occupe des frères et sœurs, paie les factures, devient le confident financier ou conjugal du parent." },
        { type: "sous-titre", texte: "· Moteur caché : « Si je ne fais pas tout ça, la maison s'effondre. Je n'ai pas le droit d'être un enfant. »" },
        { type: "sous-titre", texte: "· Devenir adulte : C'est l'adulte hyper-compétent, organisé et méritant. Mais c'est aussi une personne qui ne connaît pas le jeu, la légèreté, le lâcher-prise. Elle peut devenir parent très jeune, ou au contraire refuser farouchement d'avoir des enfants, par peur de revivre ce fardeau. En couple, elle peut tomber dans le piège de « tout gérer », puis s'épuiser et en vouloir à son partenaire de son « infantilisme ». Sa blessure : On lui a volé son enfance." },
        { type: "titre", texte: "7. L'Enfant Trophée / Le Porte-étendard" },
        { type: "sous-titre", texte: "· Origine : L'enfant n'est pas aimé pour ce qu'il est, mais pour ce qu'il représente : la réussite sociale, la beauté, le talent exceptionnel qui rejaillit sur la famille." },
        { type: "sous-titre", texte: "· Moteur caché : « Je ne suis digne d'amour et d'attention que si je brille, si je gagne, si je suis le/la meilleur(e). Ma valeur est dans mes performances et mon image. »" },
        { type: "sous-titre", texte: "· Devenir adulte : L'adulte est en quête perpétuelle de validation externe. Il/elle choisit un métier prestigieux, entretient une image impeccable sur les réseaux sociaux. Mais derrière se cache une anxiété de performance terrible et un sentiment de vide (« Qui suis-je sans mes réussites ? »). Les relations sont souvent instrumentalisées (un couple « parfait », des amis « utiles »). La chute (un échec professionnel, le vieillissement) est vécue comme une catastrophe existentielle." },
        { type: "titre", texte: "8. L'Enfant Paix / Le Ciment" },
        { type: "sous-titre", texte: "· Origine : Dans une famille où règnent les conflits ouverts (cris, violence verbale), ou au contraire un froid glacial, un enfant va développer une capacité à apaiser, calmer, créer des ponts." },
        { type: "sous-titre", texte: "· Moteur caché : « Si je suis assez calme, assez doux, assez conciliant, je peux empêcher l'explosion. Je suis le tampon. »" },
        { type: "sous-titre", texte: "· Devenir adulte : C'est la personne d'une gentillesse extrême, parfois jusqu'à l'effacement. Elle a horreur des conflits au point de se trahir elle-même pour les éviter (dire oui alors qu'elle pense non). Elle attire naturellement les personnes en détresse ou colériques, qu'elle cherche à apaiser. Son problème majeur : Elle ne sait pas exprimer sa colère, qui peut ressortir sous forme de crises d'angoisse, de somatisations (maladies physiques) ou de ressentiment passif-agressif." }
    ],
    auteurBio: "Ansima Babeho est la fondatrice d'Eloria. Élève en humanités pédagogiques avec une passion pour la psychologie, elle a créé cette plateforme après avoir constaté le besoin d'espaces d'échange authentiques entre adolescentes. Entre les ateliers qu'elle anime dans son école et les articles qu'elle rédige, elle cherche à créer des ponts entre les cœurs et les esprits."
},
    

];

// Exporter les données pour qu'elles soient accessibles
window.articlesData = articlesData;